sudo: required
services:
  - docker;

before_install:
  - docker build -t allesad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run allesad/react-test npm test -- --coverage

after_success:
  - docker build -t allesad/multi-client ./client
  - docker build -t allesad/multi-nginx ./nginx
  - docker build -t allesad/multi-server ./server
  - docker build -t allesad/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push allesad/multi-client
  - docker push allesad/multi-nginx
  - docker push allesad/multi-server
  - docker push allesad/multi-worker